### PR TITLE
Create page not found UI

### PR DESCRIPTION
**Pull request by Simon-157**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
i just viewed and just one change

don't show the Ashesi hackers league at the top with the gradient. 

show only the SVG and the "looks like..." text

**Comment by faddalibrahim** [comment]
> i just viewed and just one change
> 
> don't show the Ashesi hackers league at the top with the gradient.
> 
> show only the SVG and the "looks like..." text

ignore it. its fine

**Comment by faddalibrahim** [comment]
pull from dev on the other Errorboundary and push

**Comment by Simon-157** [comment]
> pull from dev on the other Errorboundary and push

Alright then

**Pull request merged**
