### PR TITLE
Instructions

### PR DESCRIPTION
**Pull request by Simon-157**
- created a figma design of the instructions page
- Created a pop up component for general rules that shows up few seconds upon loading the challenges page.
- Created instructions page to show all rules of the league; teams related rules, points accumulation rules, general league rules. visit /instructions route
- Tried to put a button on the home page that will be linked to the instructions page but the position of the button was hard-determining.

### CODE REVIEW

**Comment by faddalibrahim** [comment]
> * created a figma design of the instructions page
> * Created a pop up component for general rules that shows up few seconds upon loading the challenges page.
> * Created instructions page to show all rules of the league; teams related rules, points accumulation rules, general league rules. visit /instructions route
> * Tried to put a button on the home page that will be linked to the instructions page but the position of the button was hard-determining.

I'm checking this out now

**Comment by faddalibrahim** [comment]
@Simon-157 

you can go ahead and code it...also make sure its mobile friendly...if it looks too constricted on mobile you can modify the design a bit

**Comment by Simon-157** [comment]
> @Simon-157
> 
> you can go ahead and code it...also make sure its mobile friendly...if it looks too constricted on mobile you can modify the design a bit
> 
> also check the homepage design. there are 2 buttons now; one for the league rules, the other for rankings. update the code accordignly

it has already been coded

**Comment by faddalibrahim** [comment]
okay cool

But next time, let me critique the design first before you code. 

There could have been changes and all that you did would have been in vain

I might still make some changes, though

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
ok, the rules are hardcoded. Not cool!

render them with with map

```js
[
   {
      "header": "general rules,
      "rules" : [ ]
    },
    {
      "header": "points accumulation",
      "rules" : [ ]
     }
]
```

if there are more rule groups to add later, we can just add them to the array and they get rendered automatically

**Comment by Simon-157** [comment]
> okay cool
> 
> But next time, let me critique the design first before you code.
> 
> There could have been changes and all that you did would have been in vain
> 
> I might still make some changes, though

Okay sure.

**Comment by Simon-157** [comment]
> ok, the rules are hardcoded. Not cool!
> 
> render them with with map
> 
> ```js
> [
>    {
>       "header": "general rules,
>       "rules" : [ ]
>     },
>     {
>       "header": "points accumulation",
>       "rules" : [ ]
>      }
> ]
> ```
> 
> if there are more rule groups to add later, we can just add them to the array and they get rendered automatically

Alright then.

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
nice! and mobile friendly

but let's change the route name to **/rules**; sounds much better than **instructions**

**Pull request merged**
