### PR TITLE
Updatepage table

### PR DESCRIPTION
**Pull request by Simon-157**

### CODE REVIEW

**Comment by faddalibrahim** [comment]
I'm off campus currently. Will review it when I'm back

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
Good work, Simon!

But I want us to make the update buttons lighter. Here is a [codepen](https://codepen.io/faddalibrahim/pen/MWBKMXe) I have created for the buttons. 

You can either
1. Create a separate component for them and give them a nice name like LightButton
2. Or use the existing Button component; and add a prop that changes the styling.  

Dont forget to
1. create CSS variables for the colors, instead of using them directly in the styling
2. modify the styles as you fit (should they be a bit more rounded, bolded etc)..leaving that in your hands

🥂

**Comment by Simon-157** [comment]
> Good work, Simon!
> 
> But I want us to make the update buttons lighter. Here is a [codepen](https://codepen.io/faddalibrahim/pen/MWBKMXe) I have created for the buttons.
> 
> You can either
> 
> 1. Create a separate component for them and give them a nice name like LightButton
> 2. Or use the existing Button component; and add a prop that changes the styling.
> 
> Dont forget to
> 
> 1. create CSS variables for the colors, instead of using them directly in the styling
> 2. modify the styles as you fit (should they be a bit more rounded, bolded etc)..leaving that in your hands
> 
> 🥂

used the existing button component and overridden the styles with the styles props

**Comment by faddalibrahim** [comment]
good. I'm doing a couple of additions

**Comment by faddalibrahim** [comment]
Just realized the update feature has to be revamped

Don't worry, I will take care of that

**Pull request merged**
