### PR TITLE
Implement sort algorithm

### PR DESCRIPTION
**Pull request by Oheneba-Dade**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
- [ ] the sorting for "name" key doesnt work correctly (but I've fixed that below)
- [ ] Also what happens if an unexpected key is passed, say, "apple" (which is not a property of our teamScores object).  Work on throwing an error for unexpected keys

```js
function sortTable(table, key) {
   if (key === "name") {
       table.sort((a,b) => {
       const current = a.name.toLowerCase(), 
                next = b.name.toLowerCase();
      
       if(current < next) return -1
       else if(current > next) return 1
       else return 0
      })
   }
  
   table.sort((a, b) => b[key] - a[key]);
}

```

**Comment by Oheneba-Dade** [comment]
is there any specific error I should throw.

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
good attempt at using **in** to check the presence of the key

the **some** method is an overkill O(n) runtime

you could just check for the presence of the key in the first object of the table array, which will be O(1), and throw the error if its false

```js
if( (!(key in table[0])) throw new Error..

//rest of code comes
``

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
good

now there is no need for an **else if** after the key check, an **if** is enough

**Comment by Oheneba-Dade** [comment]
oh okay will do. I just thought using an if will make it check for all the cases that was why I left it that way.

**Review by faddalibrahim — APPROVED** [review]

**Pull request merged**
