### PR TITLE
create toggle text area functionality

### PR DESCRIPTION
**Pull request by Oheneba-Dade**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
cool! works as intended. but let's do a little refactoring

- [x] looks like with this implementation, we don't need the input tags and labels anymore, do we? so you will use a button here instead and attach the handleClick
- [x] store the question types (algorithms, SQL, scripting) as an array and use map to render them instead of typing out their mark up individually
- [x] instead of 
```js
	{current === "algorithms" && <AlgorithmsTextArea />}
	{current === "scripting" && <ScriptingTextArea />}
	{current === "sql" && <SqlTextArea />}
```

how about you store the question types with their text area component as key-value pairs in an object

so that depending on the value of **current**, the corresponding text area component gets picked from the object and rendered. do you get this?


```js



```

**Comment by Oheneba-Dade** [comment]
I think I get it. We will be using our custom buttons right?

**Comment by faddalibrahim** [comment]
> I think I get it. We will be using our custom buttons right? asking because of the handleclick function

Yepp 👍

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
replace 

```js
{textbox}
```

with

```js
questionTypeComponents[current]
```

as **current** changes

questionTypeComponents[current] -> questionTypeComponents["algorithms"] -> AlgorithmsTextArea

questionTypeComponents[current] -> questionTypeComponents["scripting"] -> ScriptingTextArea

questionTypeComponents[current] -> questionTypeComponents["sql"] -> SqlTextArea

do you get what's happening?

**Comment by Oheneba-Dade** [comment]
yupp

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
make this change too

from
```js
const questionTypeComponents = {
    algorithms: AlgorithmsTextArea,
    scripting: ScriptingTextArea,
    sql: SqlTextArea,
};
```

to
```js
const questionTypeComponents = {
    algorithms: <AlgorithmsTextArea/>,
    scripting: <ScriptingTextArea/>,
    sql: <SqlTextArea/>
};
```

then this

```js
{questionTypeComponents[current]()}
```

becomes

```js
{questionTypeComponents[current]}
```

**Pull request merged**
