### PR TITLE
Create button

### PR DESCRIPTION
**Pull request by Simon-157**
developed the svg button component and created a test route to test it

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
a few revamps

- [ ] instead of **InsightsSvg**, name it **InsightsIcon**, **ReportsIcon** etc
- [ ] create an **Icons.js** in **/media** and transfer the icons there
- [ ] there is supposed to be 4 icons (check the admin Figma link)
- [ ] change the **svg** prop to **icon** (my fault on that)

for the button component, you need not have separate rendering depending on the presence of the SVG prop

check for the presence of the svg (change to icon, though) within the `<button><button/>` just like for the **to**
unless you are trying a unique approach. you can brief me on that and lets see

```js
<button className={buttonStyles.svgButton} style={{...styles}}>
     {icon? icon: null}
      {to ? <Link to={to}>{text}</Link> : {text}}
  </button>
```

**Comment by Simon-157** [comment]
> a few revamps
> 
> * [ ]  instead of **InsightsSvg**, name it **InsightsIcon**, **ReportsIcon** etc
> * [ ]  create an **Icons.js** in **/media** and transfer the icons there
> * [ ]  there is supposed to be 4 icons (check the admin Figma link)
> * [ ]  change the **svg** prop to **icon** (my fault on that)
> 
> for the button component, you need not have separate rendering depending on the presence of the SVG prop
> 
> check for the presence of the svg (change to icon, though) within the `<button><button/>` just like for the **to** unless you are trying a unique approach. you can brief me on that and lets see
> 
> ```js
> <button className={buttonStyles.svgButton} style={{...styles}}>
>      {icon? icon: null}
>       {to ? <Link to={to}>{text}</Link> : {text}}
>   </button>
> ```

Okay so I was thinking the button component would be of two use. Like as you used in the rankings page with bgcolor of black and a text color of white. I was thinking since the usage in the rankings was quite different from as used in the admin page we could render it differently with different styles depending on whether an svg prop is given or not.

but I think I didn’t get it well.

**Comment by faddalibrahim** [comment]
ok

leave the default as dark bg and white text. we will use the **styles** prop to override the default where necessary

**Comment by Simon-157** [comment]
> ok
> 
> leave the default as dark bg and white text. we will use the **styles** prop to override the default where necessary

Okay, sure

**Review by faddalibrahim — APPROVED** [review]

**Pull request merged**
