### PR TITLE
feat: added protected and dynamic routing to team's page

### PR DESCRIPTION
**Pull request by WahabDev12**
Chore: Issue #27  

Feat:
1. Successfully made changes to the team's table and added the  ADD HACKER button (displays prompt on click)
2. Button, for some reason, could not accept onClick events; added a new prop (action) to handle this (was crucial for displaying the prompt)

Accessing the team page
- Redirect to this specific URL : **/team/indie-hackers**
- By default, I made the access token to the page to "indie-hackers" this can be modified in file /team/protected-routes/....

### CODE REVIEW

**Comment by faddalibrahim** [comment]
the build failed. something is wrong somewhere. check the logs and find out.

**Comment by faddalibrahim** [comment]
@WahabDev12 Ive fixed the conflicts and merged the other **team protected route issue**

pull from **development** now to get the changes, then push to this branch's PR to update it

there might be conflicts; fix them when they pop up

**Comment by WahabDev12** [comment]
> @WahabDev12 I've fixed the conflicts and merged the other **team protected route issue**
> 
> pull from **development** now to get the changes, then push to this branch's PR to update it
> 
> there might be conflicts; fix them when they pop up
> 
> if the build checks are failing, check the **Actions** tab; there will be an error log there to find out what's wrong


Was able to fix the merge conflicts with the other branch
I still do not know why the build tests keep failing

I have:
- [x] Checked the logs and did exactly what it reported

From my investigations, the problem seemed to be due to differences in React versions or something of that sort.
Need help in debugging this issue.

**Comment by faddalibrahim** [comment]
there is a voice call opened on the discord, join now

**Comment by faddalibrahim** [comment]
@WahabDev12 

what happend with this one? I don't remember a separate PR where i merged it

**Pull request closed without merging**
