### PR TITLE
Create skeleton loader 

### LINKED ISSUE #18: skeleton loader
Build for us a skeleton loader component we can customize for our needs. It should be able to morph shapes according to the props passed to it

@Oheneba-Dade 

```js
<Skeleton shape="circle"/> // renders a circle skeleton loader
<Skeleton shape="square"/> // renders a square skeleton loader
<Skeleton shape="line"/> // renders a line skeleton loader
```

image

### PR DESCRIPTION
**Pull request by Oheneba-Dade**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
looks like you didn't import the styles

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
1. remember the files naming conversion we settled on
2. .module.scss for the for file extension

did you try to render examples to view how they appear? that's what the **/pages/sandbox** is for

**Comment by Oheneba-Dade** [comment]
for some reason when I add the module it does not display which is why I took it out

**Comment by faddalibrahim** [comment]
> for some reason when I add the module it does not display which is why I took it out

yeah i know whats wrong but i ain't telling you.

just a simple question to get you thinking:  

if you have `<Skeleton shape="circle"/>` how are you selecting the styles to display based on the value of the shape?

**Comment by faddalibrahim** [comment]
its working now but the 

- [ ] shapes don't look good (look at the circle, almost like an oval)
- [ ] the skeleton animation is not really conspicuous

after fixing the above,

- [ ] scope the styles to that component alone (that's why we are using .module.scss)
@Oheneba-Dade 

image

get them to look

**Comment by faddalibrahim** [comment]
i will apply a few changes

Great work!

**Pull request merged**
