### PR TITLE
Admin navigation

### PR DESCRIPTION
**Pull request by Simon-157**

### CODE REVIEW

**Review by faddalibrahim — CHANGES_REQUESTED** [review]
- [ ] why is the **new** far off further than the rest. let them all be together
image

- [ ] the `text="New"` on the button can be `text={NEW}`, likewise for the rest of the buttons

- [ ] no need for extra markup to wrap the buttons: remove the `ul` and `li` tags. the `display:flex` can be applied to the **.navItems** class and it would still work

- [ ] what does the toggle icon do? it doesn't even show on the page

focus on fixing these for now. there is more changes i will request after this

**Comment by Simon-157** [comment]
> * [ ]  why is the **new** far off further than the rest. let them all be together
>   image
> * [ ]  the `text="New"` on the button can be `text={NEW}`, likewise for the rest of the buttons
> * [ ]  no need for extra markup to wrap the buttons: remove the `ul` and `li` tags. the `display:flex` can be applied to the **.navItems** class and it would still work
> * [ ]  what does the toggle icon do? it doesn't even show on the page

> focus on fixing these for now. there is more changes i will request after this



> * [ ]  why is the **new** far off further than the rest. let them all be together
>   image
> * [ ]  the `text="New"` on the button can be `text={NEW}`, likewise for the rest of the buttons
> * [ ]  no need for extra markup to wrap the buttons: remove the `ul` and `li` tags. the `display:flex` can be applied to the **.navItems** class and it would still work
> * [ ]  what does the toggle icon do? it doesn't even show on the page
> 
> focus on fixing these for now. there is more changes i will request after this

Alright, the toggle shows on mobile view, but I just saw the message about the mobile view for the admin page so i think i should undo it

**Comment by faddalibrahim** [comment]
yeah undo it

**Comment by faddalibrahim** [comment]
let me add the rest of the changes

- [ ] change the icon for the insights. Search for **signal** on the css.gg. it has similar style but more slick
- [ ] instead of exporting the icons all together at the bottom like this `export { PublishedIcon, ReportsIcon, InsightsIcon, NewIcon, ToggleIcon };`, add an **export** right before each component's definition
```js
export const IconName = () => {...}
```

- [ ] use a map to display the buttons instead of typing them out manually.

**Pull request merged**
